### ISSUE TITLE
Square brackets `[` inside footnotes break footnote

### ISSUE THREAD

**Issue by moritzebeling** [sylvainjule/kirby-footnotes#7]
First of all: Thank you for this wonderful plugin! And the fix to use it within blocks!

Now: Having square brackets `[` inside a footnote breaks the footnote. Which makes sense, because the regex looking out for footnotes found a `]` and thus ends the footnote.

On the other hand: It is not unusual to have square brackets inside a footnote, e.g. `[...]` or to indicate that the editor changed the exact wording of some source, resulting in something like `[^Footnote [...] text]`.

I think, the regex that looks out for `[^` should only end a footnote, when it finds a `]` AND in the meantime has found as many closing brackets as opening brackets it might have found in between. So after `[^...[` the footnote only ends on the second `]` it finds...

Thank you four considering.

**Comment by rasteiner** [comment]
I feel like counting brackets leads to a rabbit hole that doesn't end well, plus it doesn't offer a solution for every case:
What if I want to draw your avatar in a footnote? 
```
[^   moritzebeling's avatar kinda looks like :]   ]
```

Supporting escape sequences could be more flexible, even if they might require some explaining:
```
[^   moritzebeling's avatar kinda looks like :\]   ]
```

**Comment by dect0r** [comment]
Is there any progress or a temporary workaround for this?

**Comment by sylvainjule** [comment]
I have added support for escaped brackets inside a note ✓
